# Generated by Django 4.1.1 on 2022-11-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('quantite', models.IntegerField()),
                ('prix', models.FloatField()),
            ],
        ),
    ]
